---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4  # Версия Ruff
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Версия pre-commit-hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
